name: Run tests before deploying code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: secret
      DB_HOST: db-mysql-ams3-46626-do-user-8155278-0.b.db.ondigitalocean.com
      DB_PORT: 25060
      DB_USER: 2176550
      DB_PASSWORD: secret
      DB_NAME: shareameal
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client
      - name: Import database script
        run: |
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;"
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;"
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$MYSQL_ROOT_PASSWORD $DB_NAME < share-a-meal.sql
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$MYSQL_ROOT_PASSWORD -e "SHOW TABLES;"
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$MYSQL_ROOT_PASSWORD -e "SHOW VARIABLES;"
      - run: npm ci
      - run: npm test

  Railway-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Railway
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: "Current token"
        run: |
          echo "secrets.RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}"
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy server to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
